### ISSUE TITLE
Built PDF is no longer present on Bintray

### ISSUE THREAD

**Issue by JanBliznicenko** [SquareBracketAssociates/Booklet-Magritte#5]
Since Bintray does not exist anymore, there is no way to access the built PDF (that used to be on https://jfrog.com/distribution/?bintrayRD=1&file_path=magritte-wip.pdf )

**Comment by Ducasse** [comment]
Indeed I will try to fix it.

**Comment by sanjayminni** [comment]
Hi in the meanwhile could a generated PDF be shared. I have a somewhat old one which may be dated.

**Comment by jecisc** [comment]
Hi, the PDF is now generated in the latest tag of this github repository and not on bintray do I'll close this issue
